spring:
  datasource.primary:
    # TODO: 테스트 완료 후 순수 H2 메모리 설정으로 변경하기
    writer:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:
    reader:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:

  datasource.secondary:
    writer:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/order
      username: order
      password: order
    reader:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/order
      username: order
      password: order

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    # TODO: 아래 설정은 코드상에서 어떻게 넣어야 하는가?
    open-in-view: false

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE